Repository GDG-on-Campus-KNU/4th-SC-TEAM1-BE, pull requests merged in 2025-04, with the labels that each got.

#30 hotfix: solved bugs related with redis serializer setting
  src/main/java/com/gdg/Todak/common/config/RedisConfig.java
  src/main/java/com/gdg/Todak/member/service/AuthService.java
  src/main/java/com/gdg/Todak/member/service/MemberService.java
  src/main/java/com/gdg/Todak/notification/controller/NotificationController.java
  src/main/java/com/gdg/Todak/notification/service/RedisPublisherService.java
  src/main/java/com/gdg/Todak/notification/service/RedisSubscriberService.java
  src/test/java/com/gdg/Todak/member/config/RedisConfigTest.java
  src/test/java/com/gdg/Todak/member/service/MemberServiceTest.java
Labels: 😡 Bug Fix

#34 Feat: Implementing and testing point logic
  build.gradle
  src/main/java/com/gdg/Todak/common/config/RedissonConfig.java
  src/main/java/com/gdg/Todak/common/config/WebConfig.java
  src/main/java/com/gdg/Todak/diary/service/CommentService.java
  src/main/java/com/gdg/Todak/diary/service/DiaryService.java
  src/main/java/com/gdg/Todak/member/service/MemberService.java
  src/main/java/com/gdg/Todak/point/PointStatus.java
  src/main/java/com/gdg/Todak/point/PointType.java
  src/main/java/com/gdg/Todak/point/controller/PointController.java
  src/main/java/com/gdg/Todak/point/controller/advice/PointControllerAdvice.java
  src/main/java/com/gdg/Todak/point/dto/PointLogRequest.java
  src/main/java/com/gdg/Todak/point/dto/PointLogResponse.java
  src/main/java/com/gdg/Todak/point/dto/PointRequest.java
  src/main/java/com/gdg/Todak/point/dto/PointResponse.java
  src/main/java/com/gdg/Todak/point/entity/Point.java
  src/main/java/com/gdg/Todak/point/entity/PointLog.java
  src/main/java/com/gdg/Todak/point/exception/BadRequestException.java
  src/main/java/com/gdg/Todak/point/exception/ConflictException.java
  src/main/java/com/gdg/Todak/point/exception/FileException.java
  src/main/java/com/gdg/Todak/point/exception/NotFoundException.java
  src/main/java/com/gdg/Todak/point/exception/UnauthorizedException.java
  src/main/java/com/gdg/Todak/point/repository/PointLogRepository.java
  src/main/java/com/gdg/Todak/point/repository/PointRepository.java
  src/main/java/com/gdg/Todak/point/service/PointLogService.java
  src/main/java/com/gdg/Todak/point/service/PointService.java
  src/main/resources/application.properties
  src/test/java/com/gdg/Todak/diary/controller/CommentControllerTest.java
  src/test/java/com/gdg/Todak/member/service/MemberServiceTest.java
  src/test/java/com/gdg/Todak/point/controller/PointControllerTest.java
  src/test/java/com/gdg/Todak/point/entity/PointLogTest.java
  src/test/java/com/gdg/Todak/point/entity/PointTest.java
  src/test/java/com/gdg/Todak/point/repository/PointLogRepositoryTest.java
  src/test/java/com/gdg/Todak/point/repository/PointRepositoryTest.java
  src/test/java/com/gdg/Todak/point/service/PointLogServiceTest.java
  src/test/java/com/gdg/Todak/point/service/PointServiceLockTest.java
  src/test/java/com/gdg/Todak/point/service/PointServiceTest.java
Labels: ✨ Feature, ✅ Test Code

#37 Refactor: Separate lock interface and implementation, concurrency testing with springbootTest
  build.gradle
  src/main/java/com/gdg/Todak/common/lock/LockWithMemberFactory.java
  src/main/java/com/gdg/Todak/common/lock/RedisLock.java
  src/main/java/com/gdg/Todak/common/lock/RedisLockWithMemberFactory.java
  src/main/java/com/gdg/Todak/common/lock/advice/LockAdvice.java
  src/main/java/com/gdg/Todak/common/lock/exception/LockException.java
  src/main/java/com/gdg/Todak/point/controller/advice/PointControllerAdvice.java
  src/main/java/com/gdg/Todak/point/repository/PointLogRepository.java
  src/main/java/com/gdg/Todak/point/service/PointService.java
  src/test/java/com/gdg/Todak/point/config/TestRedisLockWithMemberFactory.java
  src/test/java/com/gdg/Todak/point/config/TestRedisLockWithMemberFactoryConfig.java
  src/test/java/com/gdg/Todak/point/service/PointServiceConcurrencyTest.java
  src/test/java/com/gdg/Todak/point/service/PointServiceLockTest.java
  src/test/java/com/gdg/Todak/point/service/PointServiceTest.java
Labels: ♻️ Refactoring, ✅ Test Code

#39 Deploy: 서버 및 클러스터 모니터링용 prometheus 설정
  build.gradle
  k8s/deployment.yaml.template
  src/main/java/com/gdg/Todak/common/config/WebConfig.java
  src/main/resources/application.properties
Labels: 🚀 Deploy

#42 Deploy: PR 테스트 및 품질 검사 워크플로우 설정
  .github/workflows/pr-test-quality-check.yml
  build.gradle
  sonar-project.properties
  spotbugs-exclude.xml
Labels: 🚀 Deploy

#44 chore: Add uuid generation to interceptor path
  src/main/java/com/gdg/Todak/common/config/WebConfig.java
Labels: 📦 Environment

#45 Refactor: remove user existence check from interceptor
  .gitignore
  src/main/java/com/gdg/Todak/member/Interceptor/LoginCheckInterceptor.java
  src/main/java/com/gdg/Todak/member/resolver/LoginMemberArgumentResolver.java
  src/main/java/com/gdg/Todak/member/util/JwtConstants.java
  src/main/java/com/gdg/Todak/member/util/JwtProvider.java
  src/test/java/com/gdg/Todak/member/Interceptor/LoginCheckInterceptorTest.java
  src/test/java/com/gdg/Todak/member/service/AuthServiceTest.java
Labels: ♻️ Refactoring

#47 Fix: solve pr test issue with db connection
  .github/workflows/pr-test-quality-check.yml
Labels: 😡 Bug Fix

#53 Deploy: Change the CI/CD environment db to Docker-based
  .github/workflows/docker-push-deploy.yml
  .github/workflows/pr-test-quality-check.yml
  src/test/java/com/gdg/Todak/common/config/RedissonConfigTest.java
Labels: 😡 Bug Fix, 🚀 Deploy

#51 hotfix: make to return null for invalid token claims
  .github/workflows/pr-test-quality-check.yml
  src/main/java/com/gdg/Todak/member/controller/MemberController.java
  src/main/java/com/gdg/Todak/member/service/LoginResponse.java
  src/main/java/com/gdg/Todak/member/service/MemberService.java
  src/main/java/com/gdg/Todak/member/util/JwtProvider.java
  src/test/java/com/gdg/Todak/member/service/AuthServiceTest.java
  src/test/java/com/gdg/Todak/member/service/MemberServiceTest.java
  src/test/java/com/gdg/Todak/member/util/JwtProviderTest.java
Labels: 😡 Bug Fix, ♻️ Refactoring
