Repository GDG-on-Campus-KNU/4th-SC-TEAM1-BE, pull requests merged in 2025-03, with the labels that each got.

#2 Deploy: 서버 연결 및 CI/CD
  .github/workflows/docker-push-deploy.yml
  Dockerfile
  k8s/deployment.yaml.template
Labels: 🚀 Deploy

#4 feat: 테스트용 루트경로 Json 생성
  src/main/java/com/gdg/Todak/common/controller/TestController.java
Labels: 🚀 Deploy, ✨ Feature

#8 feat: global하게 사용되는 기능 추가
  src/main/java/com/gdg/Todak/common/config/JpaAuditingConfig.java
  src/main/java/com/gdg/Todak/common/domain/ApiResponse.java
  src/main/java/com/gdg/Todak/common/domain/BaseEntity.java
Labels: ✨ Feature

#10 Feat: 일기장 기초 작업
  build.gradle
  src/main/java/com/gdg/Todak/common/config/SwaggerConfig.java
  src/main/java/com/gdg/Todak/common/config/WebConfig.java
  src/main/java/com/gdg/Todak/common/controller/TestController.java
  src/main/java/com/gdg/Todak/diary/Emotion.java
  src/main/java/com/gdg/Todak/diary/controller/DiaryController.java
  src/main/java/com/gdg/Todak/diary/dto/DiaryRequest.java
  src/main/java/com/gdg/Todak/diary/dto/DiaryResponse.java
  src/main/java/com/gdg/Todak/diary/dto/EmotionRequest.java
  src/main/java/com/gdg/Todak/diary/entity/Diary.java
  src/main/java/com/gdg/Todak/diary/repository/DiaryRepository.java
  src/main/java/com/gdg/Todak/diary/service/DiaryService.java
  src/main/resources/application.properties
Labels: ✨ Feature

#14 Feat: 인증 기능 추가
  build.gradle
  src/main/java/com/gdg/Todak/common/config/WebConfig.java
  src/main/java/com/gdg/Todak/member/Interceptor/LoginCheckInterceptor.java
  src/main/java/com/gdg/Todak/member/config/RedisConfig.java
  src/main/java/com/gdg/Todak/member/controller/AuthController.java
  src/main/java/com/gdg/Todak/member/controller/MemberController.java
  src/main/java/com/gdg/Todak/member/controller/advice/MemberControllerAdvice.java
  src/main/java/com/gdg/Todak/member/controller/request/CheckUsernameRequest.java
  src/main/java/com/gdg/Todak/member/controller/request/LoginRequest.java
  src/main/java/com/gdg/Todak/member/controller/request/LogoutRequest.java
  src/main/java/com/gdg/Todak/member/controller/request/SignupRequest.java
  src/main/java/com/gdg/Todak/member/controller/request/UpdateAccessTokenRequest.java
  src/main/java/com/gdg/Todak/member/domain/AuthenticateUser.java
  src/main/java/com/gdg/Todak/member/domain/Jwt.java
  src/main/java/com/gdg/Todak/member/domain/Member.java
  src/main/java/com/gdg/Todak/member/domain/MemberRole.java
  src/main/java/com/gdg/Todak/member/domain/Role.java
  src/main/java/com/gdg/Todak/member/exception/EncryptionException.java
  src/main/java/com/gdg/Todak/member/exception/MemberException.java
  src/main/java/com/gdg/Todak/member/exception/UnauthorizedException.java
  src/main/java/com/gdg/Todak/member/repository/MemberRepository.java
  src/main/java/com/gdg/Todak/member/repository/MemberRoleRepository.java
  src/main/java/com/gdg/Todak/member/resolver/Login.java
  src/main/java/com/gdg/Todak/member/resolver/LoginMemberArgumentResolver.java
  src/main/java/com/gdg/Todak/member/service/AuthService.java
  src/main/java/com/gdg/Todak/member/service/MemberService.java
  src/main/java/com/gdg/Todak/member/service/request/CheckUsernameServiceRequest.java
  src/main/java/com/gdg/Todak/member/service/request/LoginServiceRequest.java
  src/main/java/com/gdg/Todak/member/service/request/LogoutServiceRequest.java
  src/main/java/com/gdg/Todak/member/service/request/SignupServiceRequest.java
  src/main/java/com/gdg/Todak/member/service/request/UpdateAccessTokenServiceRequest.java
  src/main/java/com/gdg/Todak/member/service/response/CheckUsernameServiceResponse.java
  src/main/java/com/gdg/Todak/member/service/response/LogoutResponse.java
  src/main/java/com/gdg/Todak/member/service/response/MeResponse.java
  src/main/java/com/gdg/Todak/member/service/response/MemberResponse.java
  src/main/java/com/gdg/Todak/member/util/JwtProvider.java
  src/main/java/com/gdg/Todak/member/util/PasswordEncoder.java
  src/test/java/com/gdg/Todak/member/Interceptor/LoginCheckInterceptorTest.java
  src/test/java/com/gdg/Todak/member/config/RedisConfigTest.java
  src/test/java/com/gdg/Todak/member/controller/AuthControllerTest.java
  src/test/java/com/gdg/Todak/member/controller/ControllerTestSupport.java
  src/test/java/com/gdg/Todak/member/controller/MemberControllerTest.java
  src/test/java/com/gdg/Todak/member/controller/TestWebConfig.java
  src/test/java/com/gdg/Todak/member/resolver/LoginMemberArgumentResolverTest.java
  src/test/java/com/gdg/Todak/member/service/AuthServiceTest.java
  src/test/java/com/gdg/Todak/member/service/MemberServiceTest.java
Labels: ✨ Feature

#16 Deploy: 개발속성 환경변수화
  .github/workflows/docker-push-deploy.yml
  .gitignore
  Dockerfile
  src/main/java/com/gdg/Todak/common/config/WebConfig.java
  src/main/java/com/gdg/Todak/member/config/RedisConfig.java
  src/main/resources/application.properties
Labels: 🚀 Deploy

#18 Deploy: 서버에 mysql pod화 실행 및 스프링 db mysql로 변경, 환경변수 추가
  .github/workflows/docker-push-deploy.yml
  build.gradle
  src/main/resources/application.properties
Labels: 🚀 Deploy

#19 Feat: 스웨거 Authorization 기능 추가 및 member constraint 추가
  src/main/java/com/gdg/Todak/common/config/SwaggerConfig.java
  src/main/java/com/gdg/Todak/member/controller/AuthController.java
  src/main/java/com/gdg/Todak/member/controller/MemberController.java
  src/main/java/com/gdg/Todak/member/controller/advice/MemberControllerAdvice.java
  src/main/java/com/gdg/Todak/member/domain/Member.java
  src/main/java/com/gdg/Todak/member/exception/MemberException.java
  src/test/java/com/gdg/Todak/member/controller/AuthControllerTest.java
  src/test/java/com/gdg/Todak/member/controller/MemberControllerTest.java
  src/test/java/com/gdg/Todak/member/domain/MemberTest.java
Labels: ✨ Feature

#20 Hotfix/test
  src/test/java/com/gdg/Todak/member/domain/MemberTest.java
Labels: 😡 Bug Fix

#22 refactor: add basePackages to MemberControllerAdvice
  src/main/java/com/gdg/Todak/member/controller/advice/MemberControllerAdvice.java
Labels: ♻️ Refactoring

#23 Feat: Add diary and friend logic
  build.gradle
  src/main/java/com/gdg/Todak/diary/controller/DiaryController.java
  src/main/java/com/gdg/Todak/diary/controller/advice/DiaryControllerAdvice.java
  src/main/java/com/gdg/Todak/diary/dto/DiaryDetailResponse.java
  src/main/java/com/gdg/Todak/diary/dto/DiaryRequest.java
  src/main/java/com/gdg/Todak/diary/dto/DiarySearchRequest.java
  src/main/java/com/gdg/Todak/diary/dto/DiarySummaryResponse.java
  src/main/java/com/gdg/Todak/diary/dto/EmotionRequest.java
  src/main/java/com/gdg/Todak/diary/entity/Diary.java
  src/main/java/com/gdg/Todak/diary/exception/BadRequestException.java
  src/main/java/com/gdg/Todak/diary/exception/NotFoundException.java
  src/main/java/com/gdg/Todak/diary/exception/UnauthorizedException.java
  src/main/java/com/gdg/Todak/diary/repository/DiaryRepository.java
  src/main/java/com/gdg/Todak/diary/service/DiaryService.java
  src/main/java/com/gdg/Todak/friend/FriendStatus.java
  src/main/java/com/gdg/Todak/friend/controller/FriendController.java
  src/main/java/com/gdg/Todak/friend/controller/advice/FriendControllerAdvice.java
  src/main/java/com/gdg/Todak/friend/dto/FriendCountResponse.java
  src/main/java/com/gdg/Todak/friend/dto/FriendNameRequest.java
  src/main/java/com/gdg/Todak/friend/dto/FriendRequestResponse.java
  src/main/java/com/gdg/Todak/friend/dto/FriendResponse.java
  src/main/java/com/gdg/Todak/friend/entity/Friend.java
  src/main/java/com/gdg/Todak/friend/exception/BadRequestException.java
  src/main/java/com/gdg/Todak/friend/exception/NotFoundException.java
  src/main/java/com/gdg/Todak/friend/exception/UnauthorizedException.java
  src/main/java/com/gdg/Todak/friend/repository/FriendRepository.java
  src/main/java/com/gdg/Todak/friend/service/FriendService.java
  src/main/resources/application.properties
  src/test/java/com/gdg/Todak/diary/controller/DiaryControllerTest.java
  src/test/java/com/gdg/Todak/diary/entity/DiaryTest.java
  src/test/java/com/gdg/Todak/diary/repository/DiaryRepositoryTest.java
  src/test/java/com/gdg/Todak/diary/service/DiaryServiceTest.java
  src/test/java/com/gdg/Todak/friend/controller/FriendControllerTest.java
  src/test/java/com/gdg/Todak/friend/entity/FriendTest.java
  src/test/java/com/gdg/Todak/friend/repository/FriendRepositoryTest.java
  src/test/java/com/gdg/Todak/friend/service/FriendServiceTest.java
Labels: ✨ Feature, ✅ Test Code
