Repository GDG-on-Campus-KNU/4th-SC-TEAM1-BE, pull requests merged in 2025-05, with the labels that each got.

#55 Deploy ./gradlew compileJava processResources compileTestJava processTestResources test
  .github/workflows/pr-test-quality-check.yml
Labels: 🚀 Deploy

#56 Feat: admin point management page added
  build.gradle
  src/main/java/com/gdg/Todak/common/config/WebConfig.java
  src/main/java/com/gdg/Todak/member/Interceptor/AdminLoginCheckInterceptor.java
  src/main/java/com/gdg/Todak/member/Interceptor/LoginCheckInterceptor.java
  src/main/java/com/gdg/Todak/member/controller/AdminPageController.java
  src/main/java/com/gdg/Todak/member/controller/LoginPageController.java
  src/main/java/com/gdg/Todak/member/controller/MemberController.java
  src/main/java/com/gdg/Todak/member/controller/dto/LoginForm.java
  src/main/java/com/gdg/Todak/member/service/MemberService.java
  src/main/java/com/gdg/Todak/member/service/response/LoginResponse.java
  src/main/java/com/gdg/Todak/member/util/AdminPageSelectBoxItems.java
  src/main/java/com/gdg/Todak/member/util/SessionConst.java
  src/main/java/com/gdg/Todak/member/util/dto/FilterCode.java
  src/main/java/com/gdg/Todak/point/dto/PointFilterDateRange.java
  src/main/java/com/gdg/Todak/point/repository/PointLogRepository.java
  src/main/resources/application.properties
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/point.html
  src/test/java/com/gdg/Todak/member/service/AuthServiceTest.java
  src/test/java/com/gdg/Todak/member/service/MemberServiceTest.java
  src/test/java/com/gdg/Todak/point/repository/PointLogRepositoryTest.java
Labels: ✨ Feature

#57 hotfix: MockitoBean AdminLoginCheckInterceptor 의존성 추가
  src/test/java/com/gdg/Todak/common/config/RedissonConfigTest.java
  src/test/java/com/gdg/Todak/diary/controller/CommentControllerTest.java
  src/test/java/com/gdg/Todak/diary/controller/DiaryControllerTest.java
  src/test/java/com/gdg/Todak/diary/controller/ImageControllerTest.java
  src/test/java/com/gdg/Todak/diary/service/CommentServiceTest.java
  src/test/java/com/gdg/Todak/friend/controller/FriendControllerTest.java
  src/test/java/com/gdg/Todak/member/controller/ControllerTestSupport.java
  src/test/java/com/gdg/Todak/point/controller/PointControllerTest.java
  src/test/java/com/gdg/Todak/point/repository/PointLogRepositoryTest.java
Labels: 😡 Bug Fix, ✅ Test Code

#60 Feat: Added tree growth feature
  build.gradle
  sonar-project.properties
  spotbugs-exclude.xml
  src/main/java/com/gdg/Todak/member/service/MemberService.java
  src/main/java/com/gdg/Todak/point/entity/Point.java
  src/main/java/com/gdg/Todak/point/service/PointService.java
  src/main/java/com/gdg/Todak/tree/business/TreeRepository.java
  src/main/java/com/gdg/Todak/tree/business/TreeService.java
  src/main/java/com/gdg/Todak/tree/business/dto/GrowthButtonRequest.java
  src/main/java/com/gdg/Todak/tree/business/dto/TreeEntityDto.java
  src/main/java/com/gdg/Todak/tree/business/dto/TreeEntityUpdateRequest.java
  src/main/java/com/gdg/Todak/tree/business/dto/TreeInfoResponse.java
  src/main/java/com/gdg/Todak/tree/controller/TreeController.java
  src/main/java/com/gdg/Todak/tree/controller/advice/TreeControllerAdvice.java
  src/main/java/com/gdg/Todak/tree/domain/GrowthButton.java
  src/main/java/com/gdg/Todak/tree/domain/Tree.java
  src/main/java/com/gdg/Todak/tree/domain/TreeExperiencePolicy.java
  src/main/java/com/gdg/Todak/tree/exception/BadRequestException.java
  src/main/java/com/gdg/Todak/tree/exception/NotFoundException.java
  src/main/java/com/gdg/Todak/tree/repository/entity/TreeEntity.java
  src/main/java/com/gdg/Todak/tree/repository/repository/TreeJpaRepository.java
  src/main/java/com/gdg/Todak/tree/repository/repository/TreeRepositoryImpl.java
  src/test/java/com/gdg/Todak/point/entity/PointTest.java
  src/test/java/com/gdg/Todak/point/service/PointServiceConcurrencyTest.java
  src/test/java/com/gdg/Todak/point/service/PointServiceTest.java
  src/test/java/com/gdg/Todak/tree/business/TreeServiceTest.java
  src/test/java/com/gdg/Todak/tree/controller/TreeControllerTest.java
  src/test/java/com/gdg/Todak/tree/domain/TreeTest.java
  src/test/java/com/gdg/Todak/tree/repository/TreeRepositoryImplTest.java
Labels: ✨ Feature, ✅ Test Code

#62 feat: ai comment scheduling after writing diary
  src/main/java/com/gdg/Todak/diary/config/SchedulerConfig.java
  src/main/java/com/gdg/Todak/diary/service/CommentService.java
  src/main/java/com/gdg/Todak/diary/service/DiaryService.java
  src/main/java/com/gdg/Todak/diary/service/SchedulerService.java
  src/main/java/com/gdg/Todak/diary/util/OneTimeEventScheduler.java
Labels: ✨ Feature

#63 feat: ai-comment setting on-off
  src/main/java/com/gdg/Todak/member/controller/MemberController.java
  src/main/java/com/gdg/Todak/member/domain/Member.java
  src/main/java/com/gdg/Todak/member/service/MemberService.java
  src/test/java/com/gdg/Todak/member/service/MemberServiceTest.java
Labels: ✨ Feature

#69 refactor: 멤버 닉네임, 이미지 프로필 url 수정 엔드포인트 분리
  src/main/java/com/gdg/Todak/member/controller/MemberController.java
  src/main/java/com/gdg/Todak/member/controller/request/EditMemberNicknameRequest.java
  src/main/java/com/gdg/Todak/member/controller/request/EditMemberProfileImageRequest.java
  src/main/java/com/gdg/Todak/member/controller/request/EditMemberRequest.java
  src/main/java/com/gdg/Todak/member/service/MemberService.java
  src/main/java/com/gdg/Todak/member/service/request/EditMemberNicknameServiceRequest.java
  src/main/java/com/gdg/Todak/member/service/request/EditMemberProfileImageServiceRequest.java
  src/main/java/com/gdg/Todak/member/service/request/EditMemberServiceRequest.java
  src/main/java/com/gdg/Todak/member/service/response/MeResponse.java
  src/test/java/com/gdg/Todak/member/service/MemberServiceTest.java
Labels: ♻️ Refactoring

#71 Feat: Added profile image processing function
  src/main/java/com/gdg/Todak/member/controller/MemberController.java
  src/main/java/com/gdg/Todak/member/controller/advice/MemberControllerAdvice.java
  src/main/java/com/gdg/Todak/member/controller/request/EditMemberProfileImageRequest.java
  src/main/java/com/gdg/Todak/member/controller/request/ProfileRequest.java
  src/main/java/com/gdg/Todak/member/domain/Member.java
  src/main/java/com/gdg/Todak/member/exception/BadRequestException.java
  src/main/java/com/gdg/Todak/member/exception/FileException.java
  src/main/java/com/gdg/Todak/member/service/MemberService.java
  src/main/java/com/gdg/Todak/member/service/request/EditMemberProfileImageServiceRequest.java
  src/test/java/com/gdg/Todak/member/controller/MemberControllerTest.java
  src/test/java/com/gdg/Todak/tree/business/TreeServiceTest.java
Labels: ✨ Feature

#73 Feat: Added logic to view and process anonymous comments
  src/main/java/com/gdg/Todak/diary/controller/CommentController.java
  src/main/java/com/gdg/Todak/diary/dto/CommentResponse.java
  src/main/java/com/gdg/Todak/diary/dto/RevealAnonymousRequest.java
  src/main/java/com/gdg/Todak/diary/entity/CommentAnonymousReveal.java
  src/main/java/com/gdg/Todak/diary/repository/CommentAnonymousRevealRepository.java
  src/main/java/com/gdg/Todak/diary/service/CommentService.java
  src/main/java/com/gdg/Todak/diary/service/SchedulerService.java
  src/main/java/com/gdg/Todak/diary/util/AiCommentPrompt.java
  src/main/java/com/gdg/Todak/diary/util/OneTimeEventScheduler.java
  src/main/java/com/gdg/Todak/point/PointType.java
  src/main/java/com/gdg/Todak/point/entity/Point.java
  src/main/java/com/gdg/Todak/point/service/PointService.java
  src/test/java/com/gdg/Todak/diary/controller/CommentControllerTest.java
  src/test/java/com/gdg/Todak/diary/service/CommentServiceTest.java
Labels: ✨ Feature

#75 refactor: ai member Nickname changed to '토닥이'
  src/main/java/com/gdg/Todak/diary/service/CommentService.java
Labels: ♻️ Refactoring

#78 Feat: Integrate the API for pending friend requests and friend requests in rejected status and separate them into requester and acceptor positions.
  src/main/java/com/gdg/Todak/friend/controller/FriendController.java
  src/main/java/com/gdg/Todak/friend/dto/FriendRequestWithStatusResponse.java
  src/main/java/com/gdg/Todak/friend/repository/FriendRepository.java
  src/main/java/com/gdg/Todak/friend/service/FriendService.java
  src/test/java/com/gdg/Todak/friend/controller/FriendControllerTest.java
  src/test/java/com/gdg/Todak/friend/repository/FriendRepositoryTest.java
  src/test/java/com/gdg/Todak/friend/service/FriendServiceTest.java
Labels: ✨ Feature

#79 Docs: Add Readme version 1
  README.md
  images/Todak_Backend_Tech_Spec.png
  images/Todak_ERD.png
  images/Todak_Frontend_Tech_Spec.png
  images/Todak_Monitoring.png
  images/Todak_USECASE_Diagram.png
  images/Todak_Web_Server_Architecture.png
  images/Todak_new_logo.png
  images/Todak_new_logo_2.png
  images/architecture.png
  images/todak_logo.svg
Labels: 📖 Docs

#76 feat: guestbook feature added
  build.gradle
  src/main/java/com/gdg/Todak/common/config/ScheduleConfig.java
  src/main/java/com/gdg/Todak/guestbook/controller/GuestbookController.java
  src/main/java/com/gdg/Todak/guestbook/controller/advice/GuestbookControllerAdvice.java
  src/main/java/com/gdg/Todak/guestbook/controller/dto/AddGuestbookRequest.java
  src/main/java/com/gdg/Todak/guestbook/controller/dto/AddGuestbookResponse.java
  src/main/java/com/gdg/Todak/guestbook/controller/dto/DeleteGuestbookRequest.java
  src/main/java/com/gdg/Todak/guestbook/controller/dto/GetGuestbookResponse.java
  src/main/java/com/gdg/Todak/guestbook/entity/Guestbook.java
  src/main/java/com/gdg/Todak/guestbook/exception/NotFoundException.java
  src/main/java/com/gdg/Todak/guestbook/exception/UnauthorizedException.java
  src/main/java/com/gdg/Todak/guestbook/repository/GuestbookRepository.java
  src/main/java/com/gdg/Todak/guestbook/scheduler/GuestbookScheduler.java
  src/main/java/com/gdg/Todak/guestbook/service/GuestbookService.java
  src/main/java/com/gdg/Todak/member/domain/AuthenticateUser.java
  src/test/java/com/gdg/Todak/guestbook/repository/GuestbookRepositoryTest.java
  src/test/java/com/gdg/Todak/guestbook/service/GuestbookServiceTest.java
Labels: ✨ Feature

#81 Docs: Setting up swagger for notifications and guestbook features
  src/main/java/com/gdg/Todak/guestbook/controller/GuestbookController.java
  src/main/java/com/gdg/Todak/guestbook/controller/dto/GetGuestbookResponse.java
  src/main/java/com/gdg/Todak/guestbook/service/GuestbookService.java
  src/main/java/com/gdg/Todak/notification/controller/NotificationController.java
  src/test/java/com/gdg/Todak/guestbook/service/GuestbookServiceTest.java
Labels: 📖 Docs, ♻️ Refactoring

#82 refactor: refreshToken saving, authentication, reissue
  src/main/java/com/gdg/Todak/common/config/WebConfig.java
  src/main/java/com/gdg/Todak/member/controller/AuthController.java
  src/main/java/com/gdg/Todak/member/controller/MemberController.java
  src/main/java/com/gdg/Todak/member/controller/request/UpdateAccessTokenRequest.java
  src/main/java/com/gdg/Todak/member/service/AuthService.java
  src/main/java/com/gdg/Todak/member/service/MemberService.java
  src/main/java/com/gdg/Todak/member/service/request/UpdateAccessTokenServiceRequest.java
  src/main/java/com/gdg/Todak/member/util/JwtProvider.java
  src/test/java/com/gdg/Todak/member/controller/AuthControllerTest.java
  src/test/java/com/gdg/Todak/member/service/AuthServiceTest.java
  src/test/java/com/gdg/Todak/member/service/MemberServiceTest.java
Labels: ♻️ Refactoring

#85 hotfix: password change problem related to salt
  src/main/java/com/gdg/Todak/member/service/MemberService.java
Labels: 😡 Bug Fix

#90 Refactor: Clarify error message for lack of points
  src/main/java/com/gdg/Todak/member/util/JwtProvider.java
  src/main/java/com/gdg/Todak/point/entity/Point.java
  src/test/java/com/gdg/Todak/point/entity/PointTest.java
  src/test/java/com/gdg/Todak/point/service/PointServiceTest.java
Labels: ♻️ Refactoring

#92 Docs: Add Readme version 2
  README.md
  images/Todak_img.png
Labels: 📖 Docs
